<?php
require __DIR__ . '/lib.php';
if (!is_admin()) redirect('admin.php');
$id = (string)($_GET['id'] ?? 'kitchen-design-opening'); $items = load_content('services'); $service = null; $serviceIndex = null; $error = '';
foreach ($items as $index => $item) if (($item['id'] ?? '') === $id) { $service = $item; $serviceIndex = $index; }
if (!$service) { http_response_code(404); exit('サービスが見つかりません。'); }
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
 verify_csrf(); try {
  $sections=[]; for($index=0;$index<5;$index++){$current=(string)($service['sections'][$index]['image']??'');$sections[]=['heading'=>trim((string)($_POST['section_heading'][$index]??'')),'body'=>trim((string)($_POST['section_body'][$index]??'')),'image'=>upload_image('section_image_'.$index,$current),'enabled'=>isset($_POST['section_enabled'][$index])];}
  $service=['id'=>$id,'title'=>trim((string)($_POST['title']??'')),'title_en'=>trim((string)($_POST['title_en']??'')),'lead'=>trim((string)($_POST['lead']??'')),'intro'=>trim((string)($_POST['intro']??'')),'sections'=>$sections,'published'=>isset($_POST['published']),'content_revision'=>(int)($service['content_revision']??0)];
  if($service['title']==='')throw new RuntimeException('サービス名は必須です。');$items[$serviceIndex]=$service;save_content('services',$items);redirect('service-admin.php?id='.rawurlencode($id).'&saved=1');
 }catch(Throwable $exception){$error=$exception->getMessage();}
}
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>サービスページ管理</title><link rel="stylesheet" href="assets/admin.css"><link rel="stylesheet" href="assets/admin-menu-fix.css"><link rel="stylesheet" href="assets/service-admin.css"></head><body class="admin-shell"><aside><a class="admin-logo" href="admin.php">HIT OKINAWA<small>CONTENT MANAGEMENT</small></a><nav></nav></aside><script src="assets/admin-nav.js?v=4" defer></script><main class="admin-main"><header><div><p>PRO CHUBO HIT OKINAWA</p><h1>サービスページ管理</h1></div><a href="service.php?slug=<?=e($id)?>" target="_blank">公開ページを確認 ↗</a></header><?php if(isset($_GET['saved'])):?><p class="success">保存しました。</p><?php endif;?><?php if($error):?><p class="error"><?=e($error)?></p><?php endif;?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><section class="panel editor service-basics"><h2>基本情報</h2><div class="fields"><label>サービス名<input name="title" required value="<?=e($service['title'])?>"></label><label>英語表記<input name="title_en" value="<?=e($service['title_en']??'')?>"></label></div><label>リード文<textarea name="lead" rows="3"><?=e($service['lead']??'')?></textarea></label><label>導入文<textarea name="intro" rows="5"><?=e($service['intro']??'')?></textarea></label><label class="check"><input type="checkbox" name="published" <?=!empty($service['published'])?'checked':''?>>公開する</label></section><div class="service-blocks"><?php for($index=0;$index<5;$index++):$section=$service['sections'][$index]??[];$sectionEnabled=!array_key_exists('enabled',$section)||!empty($section['enabled']);?><section class="panel editor service-block"><div class="block-number">PHOTO & TEXT <?=str_pad((string)($index+1),2,'0',STR_PAD_LEFT)?><label class="block-enabled"><input type="checkbox" name="section_enabled[<?=$index?>]" <?=$sectionEnabled?'checked':''?>>この項目を使用する</label></div><div class="block-media"><?php if(!empty($section['image'])):?><img src="<?=e($section['image'])?>" alt="登録画像"><?php else:?><div>NO IMAGE</div><?php endif;?><label>写真を差し替える<input type="file" name="section_image_<?=$index?>" accept="image/jpeg,image/png,image/webp"><small>※長辺1920pxを超える画像は、比率を保って自動縮小します。</small></label></div><div><label>見出し<input name="section_heading[]" value="<?=e($section['heading']??'')?>"></label><label>本文<textarea name="section_body[]" rows="8"><?=e($section['body']??'')?></textarea></label></div></section><?php endfor;?></div><div class="save-bar"><button class="primary">サービスページを保存する</button></div></form></main></body></html>
